#------------------------------------------------------------------------------------------------------
# MO App configurations
helpertools.configurations.MOappName=TestbedConsumer
#------------------------------------------------------------------------------------------------------

# Network Configuration tags (shall be used to form the network field)
helpertools.configurations.OrganizationName=ESA
helpertools.configurations.MissionName=Testbed
helpertools.configurations.NetworkZone=Ground
helpertools.configurations.DeviceName=Workstation
#------------------------------------------------------------------------------------------------------

# Provider URI file location
providerURI.properties=providerURIs.properties

# TCP/IP protocol properties
org.ccsds.moims.mo.mal.transport.protocol.maltcp=esa.mo.mal.transport.tcpip.TCPIPTransportFactoryImpl
org.ccsds.moims.mo.mal.encoding.protocol.maltcp=esa.mo.mal.encoder.binary.fixed.FixedBinaryStreamFactory
org.ccsds.moims.mo.mal.transport.tcpip.autohost=true

# RMI protocol properties
org.ccsds.moims.mo.mal.transport.protocol.rmi=esa.mo.mal.transport.rmi.RMITransportFactoryImpl
org.ccsds.moims.mo.mal.encoding.protocol.rmi=esa.mo.mal.encoder.binary.fixed.FixedBinaryStreamFactory

org.ccsds.moims.mo.mal.transport.gen.debug=true
org.ccsds.moims.mo.mal.transport.gen.wrap=false
