# The following sets the default protocol used
#org.ccsds.moims.mo.mal.transport.default.protocol = rmi://
org.ccsds.moims.mo.mal.transport.default.protocol = maltcp://

#------------------------------------------------------------------------------------------------------

# TCP/IP protocol properties
org.ccsds.moims.mo.mal.transport.protocol.maltcp=esa.mo.mal.transport.tcpip.TCPIPTransportFactoryImpl
org.ccsds.moims.mo.mal.encoding.protocol.maltcp=esa.mo.mal.encoder.binary.fixed.FixedBinaryStreamFactory
org.ccsds.moims.mo.mal.transport.tcpip.autohost=true

# RMI protocol properties
org.ccsds.moims.mo.mal.transport.protocol.rmi=esa.mo.mal.transport.rmi.RMITransportFactoryImpl
org.ccsds.moims.mo.mal.encoding.protocol.rmi=esa.mo.mal.encoder.binary.fixed.FixedBinaryStreamFactory

#------------------------------------------------------------------------------------------------------
org.ccsds.moims.mo.mal.transport.gen.debug=true
org.ccsds.moims.mo.mal.transport.gen.wrap=false
