/**
 * This package contains classes helping with the provisioning of OBSW parameters for which values
 * are not generated by the supervisor itself.
 */
package esa.mo.nmf.nanosatmosupervisor.parameter;
