/* ----------------------------------------------------------------------------
 * Copyright (C) 2021      European Space Agency
 *                         European Space Operations Centre
 *                         Darmstadt
 *                         Germany
 * ----------------------------------------------------------------------------
 * System                : ESA NanoSat MO Framework
 * ----------------------------------------------------------------------------
 * Licensed under European Space Agency Public License (ESA-PL) Weak Copyleft – v2.4
 * You may not use this file except in compliance with the License.
 *
 * Except as expressly set forth in this License, the Software is provided to
 * You on an "as is" basis and without warranties of any kind, including without
 * limitation merchantability, fitness for a particular purpose, absence of
 * defects or errors, accuracy or non-infringement of intellectual property rights.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ----------------------------------------------------------------------------
 */
package esa.mo.nmf.ctt.services.platform.clock;

import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.ccsds.moims.mo.mal.MALException;
import org.ccsds.moims.mo.mal.MALInteractionException;
import org.ccsds.moims.mo.mal.structures.Time;
import org.ccsds.moims.mo.mal.transport.MALMessageHeader;
import org.ccsds.moims.mo.platform.clock.consumer.ClockAdapter;
import org.ccsds.moims.mo.platform.clock.consumer.ClockStub;
import esa.mo.helpertools.helpers.HelperTime;

/**
 * ClockConsumerPanel
 */
public class ClockConsumerPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(ClockConsumerPanel.class.getName());

    private final ClockStub clockService;

    public ClockConsumerPanel(ClockStub clockService) {
        initComponents();

        this.clockService = clockService;
    }

    public void init() {
        getTimeButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the
     * formAddModifyParameter. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        parameterTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        getTimeButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clock Service");
        jLabel6.setToolTipText("");

        parameterTab.setLayout(new java.awt.GridLayout(1, 1));

        getTimeButton.setText("getTime");
        getTimeButton.addActionListener(this::getTimeButtonActionPerformed);
        jPanel5.add(getTimeButton);

        parameterTab.add(jPanel5);

        timeLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            parameterTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE).addComponent(jLabel6,
                javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE).addGroup(layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                        .addContainerGap())));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
            .createSequentialGroup().addContainerGap().addComponent(jLabel6).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE).addComponent(parameterTab,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(layout.createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                            layout.createSequentialGroup().addContainerGap(46, Short.MAX_VALUE).addComponent(timeLabel,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))));
    }// </editor-fold>//GEN-END:initComponents

    private void getTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTimeButtonActionPerformed

        try {
            this.clockService.asyncGetTime(new ClockAdapter() {
                @Override
                public void getTimeResponseReceived(MALMessageHeader msgHeader, Time time, Map qosProperties) {
                    timeLabel.setText(HelperTime.time2readableString(time));
                }
            });
        } catch (MALInteractionException | MALException e) {
            LOGGER.log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_getTimeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel parameterTab;
    private javax.swing.JButton getTimeButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
