/* ----------------------------------------------------------------------------
 * Copyright (C) 2021      European Space Agency
 *                         European Space Operations Centre
 *                         Darmstadt
 *                         Germany
 * ----------------------------------------------------------------------------
 * System                : ESA NanoSat MO Framework
 * ----------------------------------------------------------------------------
 * Licensed under European Space Agency Public License (ESA-PL) Weak Copyleft – v2.4
 * You may not use this file except in compliance with the License.
 *
 * Except as expressly set forth in this License, the Software is provided to
 * You on an "as is" basis and without warranties of any kind, including without
 * limitation merchantability, fitness for a particular purpose, absence of
 * defects or errors, accuracy or non-infringement of intellectual property rights.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ----------------------------------------------------------------------------
 */
package esa.mo.nmf.ctt.services.mp;

import java.time.Instant;
import java.util.logging.Logger;
import javax.swing.JButton;
import esa.mo.nmf.ctt.services.mp.util.TimeConverter;

public class PublishedUpdatesPanel extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(PublishedUpdatesPanel.class.getName());

    public PublishedUpdatesPanel() {
        initComponents();
        refreshTime.setText(TimeConverter.convert(Instant.now().toEpochMilli()));
        this.refreshButtonActionPerformed(null);
    }

    public void setView(java.awt.Component view) {
        jScrollPane2.setViewportView(view);
    }

    public String getRefreshTime() {
        return refreshTime.getText();
    }

    public JButton getRefreshButton() {
        return refreshButton;
    }

    /**
     * This method is called from within the constructor to initialize the
     * formAddModifyParameter. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        parameterTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refreshTime = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();

        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(796, 380));
        jScrollPane2.setRequestFocusEnabled(false);

        parameterTab.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setText("Starting from");
        jPanel5.add(jLabel1);

        refreshTime.setText("yyyy-MM-dd HH:mm:ss");
        refreshTime.setMargin(new java.awt.Insets(5, 5, 5, 5));
        refreshTime.setMinimumSize(new java.awt.Dimension(190, 34));
        refreshTime.setPreferredSize(new java.awt.Dimension(190, 34));
        refreshTime.addActionListener(this::refreshTimeActionPerformed);
        jPanel5.add(refreshTime);

        refreshButton.setText("Refresh from Archive");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);
        jPanel5.add(refreshButton);

        parameterTab.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
            parameterTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE).addComponent(jScrollPane2,
                javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882,
                Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
            .createSequentialGroup().addGap(0, 0, 0).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE,
                236, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                    parameterTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void refreshTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTimeActionPerformed

    }//GEN-LAST:event_refreshTimeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel parameterTab;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField refreshTime;
    // End of variables declaration//GEN-END:variables
}
