package esa.mo.nmf.cmt.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import esa.mo.nmf.cmt.ConstellationManagementTool;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AddAdvancedSimulationGui extends JFrame {
    private final ConstellationManagementTool cmt;
    private JPanel addAdvancedSimulationGuiPanel;
    private JTextField tfFilePath;
    private JButton btnChooseFile;
    private JButton btnCreateSimulation;

    public AddAdvancedSimulationGui(ConstellationManagementTool cmt) {

        this.cmt = cmt;

        this.setContentPane(addAdvancedSimulationGuiPanel);
        this.setTitle("Create advanced Simulation");
        this.setSize(520, 123);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setVisible(true);

        btnChooseFile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String file = "";
                JFileChooser chooser = new JFileChooser();
                int clickOpen = chooser.showOpenDialog(addAdvancedSimulationGuiPanel);

                if (clickOpen == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile().getAbsolutePath();
                    tfFilePath.setText(file);
                }
            }
        });
        btnCreateSimulation.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                addAdvancedSimulation(tfFilePath.getText());
            }
        });
    }

    /**
     * Read and process the given .csv configuration file to add the segments to the constellation
     *
     * @param path .csv configuration file path
     */
    private void addAdvancedSimulation(String path) {
        HashMap<String, String[]> nanoSatConfigurations = new HashMap<>();

        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line = "#";

            while ((line = br.readLine()) != null) {
                if (line.length() < 1 || line.charAt(0) == '#') {
                    // comment or blank - ignore this line
                } else {
                    String[] values = line.split(";");
                    if (nanoSatConfigurations.get(values[0]) != null || !this.cmt.isNaNoSatSegmentNameUnique(values[0])) {
                        throw new IllegalArgumentException("Duplicated NanoSat Segment! Names must be unique.");
                    } else {
                        nanoSatConfigurations.put(values[0], new String[]{values[1], values[2], values[3], values[4], values[5], values[6]});
                    }
                }
            }

            this.cmt.addAdvancedSimulations(nanoSatConfigurations);

            this.dispose();

        } catch (IllegalArgumentException ex) {
            Logger.getLogger(ConstellationManagementTool.class.getName()).log(Level.SEVERE, "Failed to add NanoSat Segments to constellation: ", ex.getMessage());
            JOptionPane.showMessageDialog(null, "Failed to add NanoSat Segments to constellation: Names must be unique!", "Error", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found! Please select a valid .csv file.", "Error", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(ConstellationManagementTool.class.getName()).log(Level.SEVERE, "Failed to add NanoSat Segments to constellation: ", ex);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addAdvancedSimulationGuiPanel = new JPanel();
        addAdvancedSimulationGuiPanel.setLayout(new GridLayoutManager(4, 3, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Import a simulation configuration file to create an advanced simulation");
        addAdvancedSimulationGuiPanel.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Configuration .csv:");
        addAdvancedSimulationGuiPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tfFilePath = new JTextField();
        addAdvancedSimulationGuiPanel.add(tfFilePath, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnChooseFile = new JButton();
        btnChooseFile.setText("Open");
        addAdvancedSimulationGuiPanel.add(btnChooseFile, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCreateSimulation = new JButton();
        btnCreateSimulation.setText("Create Simulation");
        addAdvancedSimulationGuiPanel.add(btnCreateSimulation, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        addAdvancedSimulationGuiPanel.add(spacer1, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addAdvancedSimulationGuiPanel;
    }

}
