/* ----------------------------------------------------------------------------
 * Copyright (C) 2026      European Space Agency
 *                         European Space Operations Centre
 *                         Darmstadt
 *                         Germany
 * ----------------------------------------------------------------------------
 * System                : ESA NanoSat MO Framework
 * ----------------------------------------------------------------------------
 * Licensed under European Space Agency Public License (ESA-PL) Weak Copyleft – v2.4
 * You may not use this file except in compliance with the License.
 *
 * Except as expressly set forth in this License, the Software is provided to
 * You on an "as is" basis and without warranties of any kind, including without
 * limitation merchantability, fitness for a particular purpose, absence of
 * defects or errors, accuracy or non-infringement of intellectual property rights.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ----------------------------------------------------------------------------
 */
package esa.mo.nmf.testbed.e2e.tests;

import esa.mo.nmf.environment.Deployment;
import esa.mo.nmf.testbed.e2e.SupervisorHarness;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;

/**
 * Checks the layout of the generated NMF filesystem. These tests do not need
 * a running Supervisor: they inspect the filesystem generated by the
 * nmf-linux-maven-plugin before the test phase.
 */
public class FilesystemLayoutTest extends NMFTest {

    private static File getNmfDir() {
        String path = System.getProperty(SupervisorHarness.PROP_FILESYSTEM);
        Assert.assertNotNull("System property '" + SupervisorHarness.PROP_FILESYSTEM
                + "' is not set. Run via Maven (mvn test) so the filesystem is generated first.",
                path);
        File nmfDir = new File(path);
        Assert.assertTrue("NMF filesystem directory not found: " + nmfDir.getAbsolutePath(),
                nmfDir.isDirectory());
        return nmfDir;
    }

    // Test — The jars-nmf version directories contain only .jar files

    @Test
    public void testJarsNmfContainsOnlyJarFiles() {
        LOGGER.info(SEP + "\nRunning: testJarsNmfContainsOnlyJarFiles()\n" + SEP);
        assertOnlyJarFiles(new File(getNmfDir(), Deployment.DIR_JARS_NMF));
    }

    // Test — The jars-mission version directories contain only .jar files

    @Test
    public void testJarsMissionContainsOnlyJarFiles() {
        LOGGER.info(SEP + "\nRunning: testJarsMissionContainsOnlyJarFiles()\n" + SEP);
        assertOnlyJarFiles(new File(getNmfDir(), Deployment.DIR_JARS_MISSION));
    }

    private static void assertOnlyJarFiles(File jarsDir) {
        Assert.assertTrue("Directory not found: " + jarsDir.getAbsolutePath(),
                jarsDir.isDirectory());

        File[] versionDirs = jarsDir.listFiles();
        Assert.assertNotNull("Could not list: " + jarsDir.getAbsolutePath(), versionDirs);
        Assert.assertTrue("Expected at least one version directory in: " + jarsDir.getAbsolutePath(),
                versionDirs.length > 0);

        List<String> offenders = new ArrayList<>();
        for (File versionDir : versionDirs) {
            if (!versionDir.isDirectory()) {
                offenders.add(versionDir.getName() + " (not a version directory)");
                continue;
            }

            File[] files = versionDir.listFiles();
            Assert.assertNotNull("Could not list: " + versionDir.getAbsolutePath(), files);
            for (File file : files) {
                if (!file.isFile() || !file.getName().endsWith(".jar")) {
                    offenders.add(versionDir.getName() + File.separator + file.getName());
                }
            }
        }

        Assert.assertTrue("The " + jarsDir.getName() + " version directories must contain"
                + " only .jar files, but found: " + offenders, offenders.isEmpty());
    }
}
