/* ----------------------------------------------------------------------------
 * Copyright (C) 2026      European Space Agency
 *                         European Space Operations Centre
 *                         Darmstadt
 *                         Germany
 * ----------------------------------------------------------------------------
 * System                : ESA NanoSat MO Framework
 * ----------------------------------------------------------------------------
 * Licensed under European Space Agency Public License (ESA-PL) Weak Copyleft – v2.4
 * You may not use this file except in compliance with the License.
 *
 * Except as expressly set forth in this License, the Software is provided to
 * You on an "as is" basis and without warranties of any kind, including without
 * limitation merchantability, fitness for a particular purpose, absence of
 * defects or errors, accuracy or non-infringement of intellectual property rights.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ----------------------------------------------------------------------------
 */
package esa.mo.nmf.testbed.e2e.tests;

import esa.mo.nmf.environment.Deployment;
import esa.mo.nmf.testbed.e2e.SupervisorHarness;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import org.junit.Assert;
import org.junit.Test;

/**
 * Checks the layout of the generated NMF filesystem. These tests do not need
 * a running Supervisor: they inspect the filesystem generated by the
 * nmf-linux-maven-plugin before the test phase.
 */
public class FilesystemLayoutTest extends NMFTest {

    private static final String CHECKSUMS_FILENAME = "SHA256SUMS";
    private static final String BOOTLOADER_SCRIPT = "start_supervisor.sh";
    private static final String SETUP_USERSPACE_SCRIPT = "setup_linux_userspace.sh";

    private static File getNmfDir() {
        String path = System.getProperty(SupervisorHarness.PROP_FILESYSTEM);
        Assert.assertNotNull("System property '" + SupervisorHarness.PROP_FILESYSTEM
                + "' is not set. Run via Maven (mvn test) so the filesystem is generated first.",
                path);
        File nmfDir = new File(path);
        Assert.assertTrue("NMF filesystem directory not found: " + nmfDir.getAbsolutePath(),
                nmfDir.isDirectory());
        return nmfDir;
    }

    // Test — The jars-nmf version directories contain only .jar files (plus
    // the checksum manifest)

    @Test
    public void testJarsNmfContainsOnlyJarFiles() {
        LOGGER.info(SEP + "\nRunning: testJarsNmfContainsOnlyJarFiles()\n" + SEP);
        assertOnlyJarFiles(new File(getNmfDir(), Deployment.DIR_JARS_NMF));
    }

    // Test — The jars-mission version directories contain only .jar files
    // (plus the checksum manifest)

    @Test
    public void testJarsMissionContainsOnlyJarFiles() {
        LOGGER.info(SEP + "\nRunning: testJarsMissionContainsOnlyJarFiles()\n" + SEP);
        assertOnlyJarFiles(new File(getNmfDir(), Deployment.DIR_JARS_MISSION));
    }

    // Test — Every jars-* version directory carries its checksum manifest

    @Test
    public void testChecksumManifestsPresent() {
        LOGGER.info(SEP + "\nRunning: testChecksumManifestsPresent()\n" + SEP);
        for (String jars : new String[]{Deployment.DIR_JARS_NMF, Deployment.DIR_JARS_MISSION}) {
            for (File versionDir : new File(getNmfDir(), jars).listFiles()) {
                if (versionDir.isDirectory()) {
                    File sums = new File(versionDir, CHECKSUMS_FILENAME);
                    Assert.assertTrue("Missing checksum manifest: " + sums.getAbsolutePath(),
                            sums.isFile());
                }
            }
        }
    }

    // Test — The bootloader domain holds the three baseline files and the
    // configuration, each with the complete key set

    @Test
    public void testBootloaderDomain() throws IOException {
        LOGGER.info(SEP + "\nRunning: testBootloaderDomain()\n" + SEP);
        File bootloaderDir = new File(getNmfDir(), Deployment.DIR_BOOTLOADER);
        Assert.assertTrue("Missing directory: " + bootloaderDir.getAbsolutePath(),
                bootloaderDir.isDirectory());

        for (String filename : new String[]{Deployment.FILE_BASELINE_PRIMARY,
            Deployment.FILE_BASELINE_SECONDARY, Deployment.FILE_BASELINE_FACTORY}) {
            Properties baseline = load(new File(bootloaderDir, filename));
            for (String key : new String[]{"schema-version", "nmf-version",
                "mission-version", "java", "main-class"}) {
                Assert.assertNotNull("Missing key '" + key + "' in " + filename,
                        baseline.getProperty(key));
            }
        }

        Properties config = load(new File(bootloaderDir, Deployment.FILE_BOOTLOADER_CONFIG));
        for (String key : new String[]{"apps-isolation", "max-report-file-size-kb",
            "min-free-disk-kb"}) {
            Assert.assertNotNull("Missing key '" + key + "' in bootloader config",
                    config.getProperty(key));
        }
    }

    // Test — The bootloader script is present, executable, and static (no
    // unsubstituted or substituted generation tokens)

    @Test
    public void testBootloaderScript() throws IOException {
        LOGGER.info(SEP + "\nRunning: testBootloaderScript()\n" + SEP);
        File script = new File(getNmfDir(), BOOTLOADER_SCRIPT);
        Assert.assertTrue("Missing script: " + script.getAbsolutePath(), script.isFile());
        Assert.assertTrue("Script is not executable: " + script.getAbsolutePath(),
                script.canExecute());

        String content = new String(java.nio.file.Files.readAllBytes(script.toPath()));
        Assert.assertFalse("The bootloader script must be static: found a @TOKEN@ inside",
                content.matches("(?s).*@[A-Z_]+@.*"));
    }

    // Test — In the 'none' isolation mode no root provisioning script and no
    // legacy scripts are generated

    @Test
    public void testNoProvisioningScriptInNoneMode() {
        LOGGER.info(SEP + "\nRunning: testNoProvisioningScriptInNoneMode()\n" + SEP);
        Assert.assertFalse("setup_linux_userspace.sh must not be generated in 'none' mode",
                new File(getNmfDir(), SETUP_USERSPACE_SCRIPT).exists());
        Assert.assertFalse("fresh_install.sh is superseded and must not be generated",
                new File(getNmfDir(), "fresh_install.sh").exists());
    }

    // Test — The Boot Report directory exists

    @Test
    public void testBootReportDirectoryExists() {
        LOGGER.info(SEP + "\nRunning: testBootReportDirectoryExists()\n" + SEP);
        File reportsDir = new File(new File(getNmfDir(), Deployment.DIR_LOGS),
                Deployment.DIR_BOOTLOADER);
        Assert.assertTrue("Missing directory: " + reportsDir.getAbsolutePath(),
                reportsDir.isDirectory());
    }

    private static Properties load(File file) throws IOException {
        Assert.assertTrue("Missing file: " + file.getAbsolutePath(), file.isFile());
        Properties props = new Properties();
        try (FileInputStream in = new FileInputStream(file)) {
            props.load(in);
        }
        return props;
    }

    private static void assertOnlyJarFiles(File jarsDir) {
        Assert.assertTrue("Directory not found: " + jarsDir.getAbsolutePath(),
                jarsDir.isDirectory());

        File[] versionDirs = jarsDir.listFiles();
        Assert.assertNotNull("Could not list: " + jarsDir.getAbsolutePath(), versionDirs);
        Assert.assertTrue("Expected at least one version directory in: " + jarsDir.getAbsolutePath(),
                versionDirs.length > 0);

        List<String> offenders = new ArrayList<>();
        for (File versionDir : versionDirs) {
            if (!versionDir.isDirectory()) {
                offenders.add(versionDir.getName() + " (not a version directory)");
                continue;
            }

            File[] files = versionDir.listFiles();
            Assert.assertNotNull("Could not list: " + versionDir.getAbsolutePath(), files);
            for (File file : files) {
                if (CHECKSUMS_FILENAME.equals(file.getName()) && file.isFile()) {
                    continue; // The checksum manifest accompanies the jars
                }
                if (!file.isFile() || !file.getName().endsWith(".jar")) {
                    offenders.add(versionDir.getName() + File.separator + file.getName());
                }
            }
        }

        Assert.assertTrue("The " + jarsDir.getName() + " version directories must contain"
                + " only .jar files and " + CHECKSUMS_FILENAME + ", but found: " + offenders,
                offenders.isEmpty());
    }
}
